SELECT ENAME, SAL*12+NVL(COMM,0) AS ANNSAL
FROM EMP;

SELECT ENAME, SAL*12+NVL(COMM,0) "A N N S A L"
FROM EMP;

SELECT ENAME, SAL*12+NVL(COMM,0) "연봉"
FROM EMP;

-- Concatenaton 연산자 
select ENAME || '  IS A ' || JOB 
FROM EMP;

--DISTINCT 키워드
SELECT DEPTNO
FROM EMP;

SELECT DISTINCT DEPTNO
FROM EMP;

DESC EMP; 

SELECT *
FROM EMP
WHERE SAL >=3000;

SELECT *
FROM EMP
WHERE SAL!=3000;

SELECT EMPNO, ENAME, SAL
FROM EMP
WHERE ENAME = 'SMITH';

SELECT * FROM EMP;
DESC EMP;

--날짜 조회
SELECT * 
FROM EMP
WHERE HIREDATE <= '80/12/17';

SELECT * 
FROM EMP
WHERE DEPTNO= 10 AND JOB = 'MANAGER';

SELECT * 
FROM EMP
WHERE DEPTNO= 10 OR JOB = 'MANAGER';

SELECT * 
FROM EMP
WHERE DEPTNO= 10 AND JOB = 'MANAGER';

SELECT * 
FROM EMP
WHERE DEPTNO <> 10 ;

SELECT * 
FROM EMP
WHERE SAL NOT BETWEEN 2000 AND 3000;

SELECT * 
FROM EMP
WHERE HIREDATE BETWEEN '87/01/01' AND  '87/12/31';


SELECT *
FROM EMP
WHERE COMM NOT IN(300, 500, 1400);

SELECT *
FROM EMP
WHERE ENAME LIKE '__A%';

SELECT *
FROM EMP
WHERE ENAME NOT LIKE '%A%';

-- NULL을 위한 연산자: =을 사용하지 말고 IS를 사용

SELECT *
FROM EMP
WHERE COMM IS NOT NULL;

SELECT *
FROM EMP
ORDER BY SAL DESC;

SELECT *
FROM EMP
ORDER BY HIREDATE DESC, EMPNO ASC ;

SELECT EMPNO, ENAME
FROM EMP
WHERE ENAME LIKE 'K%';

SELECT EMPNO, ENAME
FROM EMP
WHERE ENAME LIKE '%K%';

SELECT EMPNO, ENAME
FROM EMP
WHERE ENAME LIKE '%K_';

SELECT *
FROM DUAL;

SELECT 24*60
FROM EMP;

SELECT 24*60
FROM DUAL;

SELECT SYSDATE
FROM DATE;

SELECT -10, ABS(-10)
FROM DUAL;

SELECT 34.5678, FLOOR(34.5678)
FROM DUAL;

SELECT 34.5678, ROUND(34.5678)
FROM DUAL;

SELECT 34.5678, ROUND(34.5678, 2)
FROM DUAL;

SELECT 34.5678, ROUND(34.5678, -1)
FROM DUAL;

SELECT 34.5678, TRUNC(34.5678, 2)
FROM DUAL;

SELECT MOD(27, 2), MOD(27,5), MOD(27,7)
FROM DUAL;

SELECT 'WELCOME TO ORACLE', INITCAP('WELCOME TO ORACLE')
FROM DUAL;

SELECT LENGTH('ORACLE'), LENGTH('오라클')
FROM DUAL;

SELECT LENGTHB('ORACLE'), LENGTHB('오라클')
FROM DUAL;

SELECT SUBSTRB('WELCOME TO ORACLE', 4, 3)
FROM DUAL;

SELECT INSTR('WELCOME TO ORACLE', 'LC')
FROM DUAL;

SELECT LPAD('ORACLE', 20, '#')
FROM DUAL;

SELECT RPAD('ORACLE', 20, '#')
FROM DUAL;

SELECT TRIM('  ORACLE  ')
FROM DUAL;

SELECT SYSDATE FROM DUAL;

SELECT SYSDATE-1, SYSDATE, SYSDATE+1
FROM DUAL;

SELECT HIREDATE, ROUND(HIREDATE, 'MONTH')
FROM EMP;

SELECT ENAME, SYSDATE, HIREDATE, MONTHS_BETWEEN(SYSDATE, HIREDATE)
FROM EMP;

SELECT ENAME, HIREDATE, ADD_MONTHS(HIREDATE,6)
FROM EMP;

SELECT SYSDATE, NEXT_DAY(SYSDATE, '목요일')
FROM DUAL;

SELECT HIREDATE, LAST_DAY(HIREDATE)
FROM EMP;

SELECT SYSDATE, TO_CHAR(SYSDATE, 'YYYY-MM-DD')
FROM DUAL;

SELECT SYSDATE, TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS')
FROM DUAL;

SELECT ENAME, SAL, TO_CHAR(SAL, 'L999,999')
FROM EMP;

SELECT ENAME, HIREDATE FROM EMP
WHERE HIREDATE = TO_DATE(19810220, 'YYYY/MM/DD');

SELECT TRUNC(SYSDATE-TO_DATE('2022/03/02', 'YYYY/MM/DD'))
FROM DUAL;

SELECT TO_NUMBER('20,000', '99,999') - TO_NUMBER('10,000', '99,999')
FROM DUAL;

SELECT 20,000 - 10,000
FROM DUAL;

SELECT ENAME, SAL, COMM, SAL*12+COMM, NVL(COMM,0), SAL*12+NVL(COMM,0)
FROM EMP
ORDER BY JOB;

SELECT ENAME, DEPTNO, DECODE(DEPTNO, 10, 'ACCOUNTING', 
    20, 'RESERCH', 30, 'SALES', 40, 'OPERTION') AS DNAME
FROM EMP;

SELECT ENAME, DEPTNO,
    CASE WHEN DEPTNO = 10 THEN 'ACCOUNTING'
    WHEN DEPTNO = 20 THEN 'RESEARCH'
    WHEN DEPTNO = 30 THEN 'SALES'
    WHEN DEPTNO = 40 THEN 'OPERATIONS'
    END AS DNAME
    FROM EMP;
    
    SELECT HIREDATE, TO_CHAR(HIREDATE, 'YYYY/MM/DD')
    FROM EMP;
    
    SELECT ENAME, NVL(TO_CHAR(MGR),'CEO')
    FROM EMP
    WHERE MGR IS NULL;
 
